[platformio]
name = mu
description = radio that talks back
default_envs =
  esp32-s3-devkitc-1
  ; seeed_xiao_esp32s3
;   uno
  ; giga

[env]
; build_flags = -v
targets =
  ; uploadfs
  upload
  monitor
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
; upload_protocol = espota
; upload_port = 192.168.0.255
; upload_flags =
    ; --port=8266 ; default

monitor_filters = time

; lib_deps =
    ; adafruit/Adafruit LPS2X@^2.0.6
    ; adafruit/Adafruit TMP117@^1.0.3

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.filesystem = spiffs
; test_port = hwgrep://941383986071f011a93cf99e1045c30f
; upload_port = hwgrep://941383986071f011a93cf99e1045c30f
; monitor_port = hwgrep://941383986071f011a93cf99e1045c30f
lib_deps =
    adafruit/Adafruit NeoPixel@^1.15.2
    esp32async/ESPAsyncWebServer@^3.9.0
    madhephaestus/ESP32Servo

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
board_build.filesystem = spiffs
test_port = hwgrep://D8:3B:DA:74:6B:FC
upload_port = hwgrep://D8:3B:DA:74:6B:FC
monitor_port = hwgrep://D8:3B:DA:74:6B:FC
; board_build.filesystem = spiffs ; see docs.platformio.org/en/latest/platforms/espressif32.html#uploading-files-to-file-system
; test_ignore = off_switch
lib_deps =
    esp32async/ESPAsyncWebServer@^3.9.0

[env:giga]
platform = ststm32
board = giga_r1_m7
lib_deps =
    arduino-libraries/Arduino_GigaDisplay@^1.0.2
